### ISSUE TITLE
Enhance the Readme section

### ISSUE THREAD

**Issue by Amishakumari544** [WasmEdge/docs#10]
For now, there is very few information added in the Readme.md file. We should enhance this a little bit.

What do you think? @alabulei1

**Comment by Pritishchugh22** [comment]
Dear @Amishakumari544 @alabulei1 
I am writing this to express my interest in participating in the Google Season of Docs program, 2023. I am a final year student at IIT Mandi, pursuing Bachelors of Technology in Computer Science. I am doing minors in Data Science and have done a significant number of courses as well as projects in this domain.
Could you please guide me on how to proceed. I would appreciate any advice or recommendations you may have regarding the project. Also, I think this issue can be a good start for me and will make me stand out from the other participants.

Thanks and Regards
Pritish Chugh

**Comment by bupd** [comment]
@Amishakumari544 @alabulei1 

It would be nice, if we add these to the **Readme.md** file.

- Project name and description
- Installation instructions
- Usage instructions
- Features and functionalities
- How to contribute to the project
- License information
- Contact information for the project owner or maintainers
- Links to additional resources or documentation
- Frequently Asked Questions (FAQs)
- Known issues or bugs and how to report them

Including these details can make it easier for others to understand and use the project, as well as encourage contributions and collaborations from other developers. Eventhough we have our site it will be more useful if we add it here too.

**Comment by alabulei1** [comment]
Hi  @Amishakumari544, @Pritishchugh22,and @bupd 

I apologize for my late reply. Somehow, I didn't notice this issue. Yes. the README.md must need to be updated before we go online. Thanks for your suggestion. Much appreciated.

#12 has added some simple content. Feel free to create a PR to add your thoughts.

**Comment by Pritishchugh22** [comment]
Hi @alabulei1 
I have made some changes to the README.md file and have tried to add the important information I believe need to be present on the repository. I have opened a pull request for the same. I wish if you could please have a look at it and suggest any necessary changes that might be required.
Regards
Pritish
