### ISSUE TITLE
Bug: Mermaid not rendered

### ISSUE THREAD

**Issue by q82419** [WasmEdge/docs#119]
### Describe the bug.

The mermaid graph in [this page](https://wasmedge.org/docs/contribute/internal) is not rendered.

### Expected behavior.

Render the graph.

### Operating Environment

MacOS

**Comment by mhmohona** [comment]
In #105 I have added necessary dependencies for mermaid. Once that PR is merged, all mermaid diagram will be rendered successfully.

**Comment by adithyaakrishna** [comment]
@q82419 Can we go ahead and close this issue now that the mermaid diagrams are working perfectly?

**Comment by alabulei1** [comment]
It looks great! I will close this issue.
