### ISSUE TITLE
Bug: The Rust codes are not colorized

### ISSUE THREAD

**Issue by q82419** [WasmEdge/docs#120]
### Describe the bug.

Such as the Rust code in [the pages](https://wasmedge.org/docs/develop/rust/hello_world), the code blocks are not colorized.
As the previous [docs in mdbook](https://wasmedge.org/book/en/sdk/rust/say_hello.html), it should be colorized.

### Operating Environment

MacOS

**Comment by adithyaakrishna** [comment]
Taking this up :)

**Comment by adithyaakrishna** [comment]
@q82419 Fixed it above
