### ISSUE TITLE
[Feature] - Docusaurus SEO for Docs

### ISSUE THREAD

**Issue by adithyaakrishna** [WasmEdge/docs#133]
**Description:**

Work on improving the SEO of the site through docusaurus

More Info: https://docusaurus.io/docs/seo

**Comment by adithyaakrishna** [comment]
@alabulei1 Could you please assign this to me?

**Comment by alabulei1** [comment]
@adithyaakrishna  May I ask what have you done to improve SEO?

**Comment by adithyaakrishna** [comment]
@alabulei1 The changes for SEO are in this PR, #145 and I have added the below mentioned changes

<img width="1270" alt="Screenshot 2023-08-21 at 1 15 52 PM" src="https://github.com/WasmEdge/docs/assets/23498248/fadcbc07-ca5c-4ec5-b1a5-49d1e7e093fc">
