### ISSUE TITLE
[DOCS] The OpenVINO is updated to 2023 edition. Related docs should be updated

### ISSUE THREAD

**Issue by hydai** [WasmEdge/docs#136]
### Description

See https://github.com/WasmEdge/WasmEdge/pull/2636

The OpenVINO is updated. So we will need to update the corresponding documents.

**Comment by hydai** [comment]
Hi @Mash707 
I think there is one page needs to update: https://github.com/WasmEdge/docs/blob/main/docs/contribute/source/plugin/wasi_nn.md?plain=1

**Comment by Mash707** [comment]
> Hi @Mash707 
> 
> I think there is one page needs to update: https://github.com/WasmEdge/docs/blob/main/docs/contribute/source/plugin/wasi_nn.md?plain=1

Thank you. I will start working on it and will give a PR soon.
