### ISSUE TITLE
Add docs link for each plugin

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/docs#163]
### Is your feature request related to a problem? Please describe.

Readers can find the plugins crate on the plugin page, but it's difficult to locate the documentation on how to use them. Adding a link for each plugin would be helpful.
https://wasmedge.org/docs/start/wasmedge/extensions/plugins/#official-released-plug-ins

### Describe the solution you'd like.

As an example, it would be beneficial to include a hyperlink https://wasmedge.org/docs/develop/rust/wasinn/pytorch for the WASI-NN platform that utilizes the Pytorch backend.

**Comment by ATREAY** [comment]
Hey @alabulei1, can I take this issue? 
Quick question: should we add a link to the repo for each widget or just the documentation link?

**Comment by ATREAY** [comment]
Hey @alabulei1 ,

I would like to inquire about the status of this issue. Is this issue still open?

**Comment by Mash707** [comment]
Hi @ATREAY are you working on this issue? If not I can provide a PR. Thank you.

**Comment by ATREAY** [comment]
Hey @Mash707, I'm not currently working on this issue since it's not assigned to me.
Feel free to proceed with your PR, but I'd recommend reaching out to @alabulei1 to get this issue assigned to you officially.
