### ISSUE TITLE
[Feat] - Add Caching Capabilities to Workflow

### ISSUE THREAD

**Issue by adithyaakrishna** [WasmEdge/docs#17]
**Description:**

The Deploy script [here](https://github.com/WasmEdge/docs/blob/main/.github/workflows/deploy.yml),  can be improved by adding caching capabilities to the workflow to reduce the CI time.

**Comment by Preshh0** [comment]
Hello!
I'd like to work on this, how do I get started?

**Comment by alabulei1** [comment]
Closed this issue because #24 has solved it.
