### ISSUE TITLE
An issue in Built-in modules docs

### ISSUE THREAD

**Issue by ShayanShiravani** [WasmEdge/docs#171]
### Description

Hi.
The bash script explained in the following to map the host path to /modules directory is wrong.
https://github.com/WasmEdge/docs/blob/80b2a5fe7753e1e727b390d7d304d48e3b34133e/docs/develop/javascript/modules.md?plain=1#L20 
According to the wasmedge --help, it's correct to write wasmedge --dir /modules:/host/os/path

### Screenshots

![Screenshot from 2023-09-17 17-12-10](https://github.com/WasmEdge/docs/assets/22572845/17ec226e-447d-43c7-bae3-acb98c535377)

**Comment by L-jasmine** [comment]
You're right. Thank you for your issue
