### ISSUE TITLE
[DOCS] Possibly Rustls Plug-in typo

### ISSUE THREAD

**Issue by morristai** [WasmEdge/docs#212]
### Description

I came across this [issue](https://github.com/WasmEdge/WasmEdge/discussions/3182) and noticed that the title `Rusttls` does not seem to align with its content and the crate name - `Rustls`. Is this intentional or is it a typo? I've found that some references in the documentation use `Rusttls`. If it's a typo, I can submit a pull request to address this issue.

### Screenshots

<img width="874" alt="typo" src="https://github.com/WasmEdge/docs/assets/10728152/b2c5745d-aefb-4041-91ea-2658a25cdfbc">

**Comment by alabulei1** [comment]
Hi @morristai 

Thanks for pointing this out. I think I made a typo here. A PR is welcome! Thanks you in advance.
