### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by kelvinparmar** [WasmEdge/docs#218]
### Description

In docs, there is a section comparison between WebAssembly and Docker the provided link is not working.

### Screenshots

![screencapture-wasmedge-org-docs-start-wasmedge-comparison-2024-03-05-11_10_25](https://github.com/WasmEdge/docs/assets/94775043/a16d7337-7f44-4996-98fb-fee90ef65de4)
![screencapture-wasmedge-org-wasm-docker-2024-03-05-11_10_37](https://github.com/WasmEdge/docs/assets/94775043/c6a7f12a-20c1-4596-884f-1f815f6b167b)

**Comment by hydai** [comment]
@alabulei1 Please check the link.

**Comment by kelvinparmar** [comment]
@hydai  I am able to work on this issue please provide me the link.

**Comment by alabulei1** [comment]
The correct link is here. https://wasmedge.org/wasm_linux_container/

If you'd like to contribute to, just do it. Thank you so much!

**Comment by kelvinparmar** [comment]
Yes I will

**Comment by arujjval** [comment]
@alabulei1 @kelvinparmar are you still working on this?

**Comment by angad-singhh** [comment]
> The correct link is here. https://wasmedge.org/wasm_linux_container/

Hey @alabulei1 ,
The link on the docs is now working, but in the [docs](https://wasmedge.org/docs/start/wasmedge/comparison/), the [page](https://wasmedge.org/wasm_linux_container/) it opens is about comparing **WebAssembly vs Linux Container** not the WebAssembly vs. Docker. 

**Check here** 

>https://github.com/WasmEdge/docs/assets/108326021/ba773a90-2801-4a76-b899-05011c6b6350

**Solution:**

- Either we have to correct the WasmEdge docs/comparison section to specify that the comparison is between WebAssembly vs Linux Container
- or we have to change the link, and the page link which shows WebAssembly vs. Docker.
- Either of the above, if required and you agree, please assign me I'm ready to solve and create a PR.

**Comment by hydai** [comment]
@alabulei1 
What's the status of this issue? Is it resolved?

**Comment by kelvinparmar** [comment]
@hydai Its completed
![Uploading screencapture-wasmedge-org-wasm-linux-container-2024-06-13-14_13_53.png…]()

**Comment by hydai** [comment]
Closing this. If there is any other issue, please feel free to create a new one.
