### ISSUE TITLE
[DOCS]  Enable Search for the dcos

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/docs#28]
### Description

Now we don't support search for the docs. However, it's a must-have thing for users to find the content they need quickly.

### Additional information

Need to apply a token from docusaurus.

**Comment by kokamkarsahil** [comment]
The owner of the website have to apply at https://docsearch.algolia.com/apply/ to get token or someone who has obtain permission from the owner can apply.

There is another way to use local search for example: https://github.com/easyops-cn/docusaurus-search-local it's supports zn too

**Comment by alabulei1** [comment]
Thanks @kokamkarsahil
