### ISSUE TITLE
[DOCS] Folder names in repository do not match titles on website

### ISSUE THREAD

**Issue by Mackenzie-OO7** [WasmEdge/docs#35]
### Description

I've noticed that some the folder names in the repository for this project do not match the titles used on the hosted website. This can be confusing for contributors who are trying to locate specific files.

To address this issue, I would like to u[date the folder names to match their corresponding titles on the website. This will improve the organization and clarity of the project for everyone involved.

I would like to take on this task and submit a pull request.

### Screenshots

I wanted to edit this page, and I had a little trouble locating it on my machine

![Screenshot 2023-04-26 154741](https://user-images.githubusercontent.com/97461848/234614963-0d5a00b7-96ed-4673-b8a6-d994e5b7bcaa.png)

It was located in a folder named 'os' which was in the 'Contribute' folder, neither of which are titles in the hosted site.

![Screenshot 2023-04-26 154826](https://user-images.githubusercontent.com/97461848/234615018-6ac44a5d-6110-4622-a7fa-dae401ebf115.png)

**Comment by alabulei1** [comment]
Hi @Mackenzie-OO7 

To make the link shorter, I use `windows` to present `Build on Windows`. The link is here: https://github.com/wasmedge/docs/blob/main/docs/contribute/source/os/windows.md

Do you mean you want to change the md file name to match the docs' title?

**Comment by Mackenzie-OO7** [comment]
> Do you mean you want to change the md file name to match the docs' title?

Yes, that's what I mean.

**Comment by Bhardwaj-Himanshu** [comment]
@Mackenzie-OO7 We need not to change the file name to change the `tab-name` or `title of page` which is displayed over the website.
like this-
```md
---
title: my hello page title
description: my hello page description
hide_table_of_contents: true
---

# Hello

This is a sample code.
```

We could also rename the pages as you suggested, but `that would oblige us to change the links of that file in every other file which could raise some unresolved issues`

Hope this gives you a little bit of hint/solution about your query!
Thanks

**Comment by alabulei1** [comment]
I agree with @Bhardwaj-Himanshu. We should take the URL carefully.
