### ISSUE TITLE
[DOCS] No pages and content for "FAQ" and "Best Practices"

### ISSUE THREAD

**Issue by Mackenzie-OO7** [WasmEdge/docs#37]
### Description

I noticed that there is no content for "Frequently asked questions" and "Best Practices with WasmEdge", in the documentation and I would like to work on this.

For the Frequently asked Questions, I would go through WasmEdge's community channels, make a compilation of the recurring questions, as well as similar ones, along with the solutions provided. 

As for the Best Practices, I consider myself a beginner with WasmEdge, so while I can come up with a draft of Best Practices, I would require the help of a community member with more experience to answer questions I will have, and also review my drafts.

I believe that this is going to be a great addition, and improvement to the docs, seeing as both sections are essential in any documentation.

**Comment by alabulei1** [comment]
That would be great! We can start from the FAQ page.

**Comment by Mackenzie-OO7** [comment]
> That would be great! We can start from the FAQ page.

Thanks! I'll get started on the FAQ first.

**Comment by adithyaakrishna** [comment]
@Mackenzie-OO7 Could you please lmk if you have any update on this?

**Comment by Mackenzie-OO7** [comment]
> @Mackenzie-OO7 Could you please lmk if you have any update on this?

Hi, I'm sorry I got sidetracked working on something else

**Comment by mhmohona** [comment]
Hello @Mackenzie-OO7, thanks for bringing up this issue. I have initiated the FAQ file and added some FAQs. 
If you work on more faqs feel free to add more there!
