### ISSUE TITLE
Feature Request: Create Page for WasmEdge talks

### ISSUE THREAD

**Issue by kokamkarsahil** [WasmEdge/docs#57]
### Is your feature request related to a problem? Please describe.

As one who got to know about wasm-edge by watching talks, it's difficult to find all the wasm-edge related talks in one place.

### Describe the solution you'd like.

Create a `/talks` pages to list all the wasm-edge related talks in chronological order with related assets to talks like https://github.com/second-state/kubecon-eu-2023.

### Describe alternatives you've considered

Creating a YouTube playlist for all the talks.

**Comment by alabulei1** [comment]
That's a great idea! Is the page link wasmedge.org/docs/talks?

**Comment by kokamkarsahil** [comment]
> That's a great idea! Is the page link wasmedge.org/docs/talks?

`wasmedge.org/talks` this can be doing within docs itself via `docs/src/pages/` directory. I will create a demo page for it as soon as possible.

**Comment by alabulei1** [comment]
wasmedge.org/docs/talks also works. Thank you so much!

**Comment by kokamkarsahil** [comment]
> wasmedge.org/docs/talks also works. Thank you so much!

Nope, happy to help out. I am also experimenting with creating a release page.

![image](https://user-images.githubusercontent.com/84327775/237022986-e75549ea-7b14-4540-9f03-88cc6b4162df.png)

I will create a draft PR if all works well!
