### ISSUE TITLE
Bug: Footer Logo and Header Logo should be the same

### ISSUE THREAD

**Issue by adithyaakrishna** [WasmEdge/docs#61]
### Describe the bug.

The footer and header menu logo at https://wasmedge.org/docs are not the same and this needs to be fixed

### Describe the steps to reproduce the behavior.

Go to https://wasmedge.org/docs and Scroll down to the footer, you would notice that the logo is different than the one in the header menu

### Expected behavior.

Logos should be the same

### Screenshots.

<img width="1701" alt="Screenshot 2023-05-09 at 6 06 32 PM" src="https://github.com/WasmEdge/docs/assets/23498248/78bb815a-8477-4168-945e-5f13bbfaa5a6">

### Operating Environment

macOS

**Comment by adithyaakrishna** [comment]
@alabulei1 Could you please let us know which is the right one so that the logos can be made consistent across the site?

**Comment by alabulei1** [comment]
Hi @adithyaakrishna 

Actually, they are the same thing. The logo on the header only uses the icon. The logo in the footer uses icon+text.

BTW, the CI of your last PR failed. Could you help fix it?

**Comment by alabulei1** [comment]
You can find all the WasmEdge logo here: https://github.com/cncf/artwork/blob/master/examples/sandbox.md#wasedgeruntime-logos

**Comment by adithyaakrishna** [comment]
@alabulei1 The issue wrt to the CI seems to be fixed from this https://github.com/WasmEdge/docs/actions/runs/4921661011 action. The changes from that PR are also in production now at https://wasmedge.org/docs

**Comment by rum1887** [comment]
is the issue open?

**Comment by adithyaakrishna** [comment]
@rum1887 Yes, please feel free to take it :)

**Comment by adithyaakrishna** [comment]
With respect to this comment, https://github.com/WasmEdge/docs/issues/61#issuecomment-1540143663, IMO we can ignore this issue as the logo is just missing the text. Not necessarily a important task. I will go ahead and close this :)
