### ISSUE TITLE
Feature Request: Release Page

### ISSUE THREAD

**Issue by kokamkarsahil** [WasmEdge/docs#63]
### Is your feature request related to a problem? Please describe.

Displaying releases at one place for all Wasmedge related projects.

### Describe the solution you'd like.

Creating a release page with all the project by fetching Changelog from main repos.

Here is WIP demo for release page: https://render.sahil.world/docs/releases

**Comment by adithyaakrishna** [comment]
@kokamkarsahil Will you be working on this issue?

**Comment by kokamkarsahil** [comment]
> @kokamkarsahil Will you be working on this issue?

Yeah , I am working on it. Opened this issue to get any feedback
