### ISSUE TITLE
Add a twitter card for WasmEdge/Docs

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/docs#76]
### Is your feature request related to a problem? Please describe.

WasmEdge's docs don't have a preview card.

<img width="541" alt="image" src="https://github.com/WasmEdge/docs/assets/45785633/bfe099b8-50f6-4903-9c03-aa265f66fc0b">

### Describe the solution you'd like.

Follow the instruction from docusarus to add one: https://docusaurus.io/docs/next/api/themes/configuration#meta-image

**Comment by alabulei1** [comment]
We can use the stacked WasmEdge logo as the preview image.

**Comment by eshaanagarwal** [comment]
Great ! I would like to take this up. i will send the pull request in some time.

**Comment by eshaanagarwal** [comment]
> We can use the stacked WasmEdge logo as the preview image.

can you please share the link to this logo?

**Comment by kokamkarsahil** [comment]
> can you please share the link to this logo?

You can the assets here: https://github.com/WasmEdge/docs/tree/main/static/img

**Comment by Lucif3r-in** [comment]
@eshaanagarwal are you working on this?

**Comment by adithyaakrishna** [comment]
@eshaanagarwal Wanna take this up?

**Comment by adithyaakrishna** [comment]
@Lucif3r-in I dont have the permissions to assign you to this, but you can work on it and send a PR which I will be glad to review :)

**Comment by adithyaakrishna** [comment]
@Lucif3r-in You would need to make the change in this file, https://github.com/WasmEdge/docs/blob/main/docusaurus.config.js and the required change and how to do it can be found here, https://docusaurus.io/docs/next/api/themes/configuration#meta-image

**Comment by Lucif3r-in** [comment]
![image](https://github.com/WasmEdge/docs/assets/85403534/5ce75517-8fd2-44c9-88c8-3c4b4a872b8e)
@adithyaakrishna I am getting this error when I try to commit my changes. Can you tell me where I am going wrong?
P.s- I have tried npm run lint:style

**Comment by adithyaakrishna** [comment]
@Lucif3r-in I will send a fix for this, for now you can commit using a flag `--no-verify` which will make your command as `git commit -m "fix: add meta image for twitter card`

**Comment by Lucif3r-in** [comment]
Done @adithyaakrishna
