### ISSUE TITLE
GSoD workplace: Create new WasmEdge plug-in contributor guides in C, C++, and Rust

### ISSUE THREAD

**Issue by mhmohona** [WasmEdge/docs#85]
**Project Name**: Create new WasmEdge plug-in contributor guides in C, C++, and Rust

**Description**:
This issue serves as a centralized place to track the progress of the WasmEdge plug-in contributor guides project, which is part of the [Google Season of Docs (GSoD) ](https://github.com/WasmEdge/GSoD2023)program. The objective of this project is to create comprehensive guides for developers who want to contribute to the WasmEdge ecosystem by implementing plug-ins in C, C++, or Rust.

The purpose of this issue is to keep a record of the pull requests (PRs) submitted by me throughout the course of this project. By linking the PRs here, it will be easier to track and review the progress and provide feedback as needed.

**Project Details**:
- GSoD Project Name: Create new WasmEdge plug-in contributor guides in C, C++, and Rust
- Contributor: @mhmohona 
- Mentor: @juntao, @alabulei1, @q82419

**Outline**

- Getting Started with WasmEdge Plugins
  * What is a WasmEdge plugin?
  * How can WasmEdge plugins be used?
  * Benefits of using WasmEdge Plug-in System

- Developing WasmEdge Plugins
  * Requirements for developing a WasmEdge plugin
  * Choosing a programming language
    * C
    * C++
    * Rust 
  * Setting up the development environment
  * Creating a WasmEdge plugin project
  * Defining the plugin API
  * Implementing the plugin API
  * Compiling the WasmEdge plugin
 
- WasmEdge Plugin API Reference 
  - Loading a WasmEdge plugin
  - Registering the plugin API
  - Importing the plugin modules
  - Sample application that uses a WasmEdge plugin
  - Examples of WasmEdge Plug-ins
    - Overview of the WasmEdge Plug-ins
    - WasmEdge-Process Plug-in
    - WASI-Crypto Plug-in
    - WASI-NN Plug-in with OpenVINO backend
    - WASI-NN Plug-in with PyTorch backend
    - WASI-NN Plug-in with TensorFlow-Lite backend
    - WasmEdge-HttpsReq Plug-in

- Understanding WasmEdge Plugins
  - Best Practices for Developing WasmEdge Plug-ins
    - Security best practices
    - Performance best practices
    - Compatibility best practices
    - Documentation best practices
  - Error handling
    - How to handle errors in WasmEdge plugins
    - Tips for avoiding common error-handling pitfalls
  - Debugging
   - How to debug WasmEdge plugins
   - Tips for using WasmEdge's debugging tools
  - Testing
    - How to test WasmEdge plugins
    - Tips for writing effective WasmEdge unit tests

- Conclusion
- Recap of WasmEdge Plug-in System
- Future Development Roadmap

**PRs Submitted**:
- #105 
- #106  
- #107 
- #102

**Comment by mhmohona** [comment]
Update until now -



Improved existing documentation -

- Plugin Introduction -->  #105 
- Loadable Plugin --> #106 
- Currently released Plugin --> #107 
  
Created new documentation - 

- Developing WasmEdge Plugins --> #102 
  * Requirements for developing a WasmEdge plugin
  * Choosing a programming language
    * C
    * C++
    * Rust 
  * Setting up the development environment
  * Creating a WasmEdge plugin project
  * Defining the plugin API
  * Implementing the plugin API
  * Compiling the WasmEdge plugin
  
Currently working on - 
- WasmEdge Plugin API Reference --> #116
  - Loading a WasmEdge plugin
  - Registering the plugin API
  - Importing the plugin modules
  - Sample application that uses a WasmEdge plugin
  - Examples of WasmEdge Plug-ins
    - Overview of the WasmEdge Plug-ins
    - WasmEdge-Process Plug-in
    - WASI-Crypto Plug-in
    - WASI-NN Plug-in with OpenVINO backend
    - WASI-NN Plug-in with PyTorch backend
    - WASI-NN Plug-in with TensorFlow-Lite backend
    - WasmEdge-HttpsReq Plug-in

**Comment by alabulei1** [comment]
@mhmohona Please update your work progress here. Thanks.

**Comment by mhmohona** [comment]
Update till July 31 - 

- Followed up with mentors.
- Finalized the #102

**Comment by mhmohona** [comment]
Update till September - 
Worked on following PRs 
- #146 
- #144 
- #153
