### ISSUE TITLE
Issue and PR template

### ISSUE THREAD

**Issue by octonawish-akcodes** [WasmEdge/docs#9]
It would be nice to have both Issue and PR template in this repo which will help in formatting the issue and proposed changes in a very informative way to the other contributors and maintainers of this project.

I am willing to take this issue, can you assign it to me @alabulei1

**Comment by alabulei1** [comment]
Hi @octonawish-akcodes,

Thanks for your fantastic suggestion and your work. Let's do it.

**Comment by adithyaakrishna** [comment]
@alabulei1 Can I take this up?
