### ISSUE TITLE
Discard the old book and migrate the book content to this new repo

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/docs#94]
### Is your feature request related to a problem? Please describe.

The maintainers and community only need one single source for docs. Two docs will make it confused.

### Describe the solution you'd like.

For this issue, we have three things to do.

1. Discard the old book, see an ongoing PR [1](https://secondstate.slack.com/archives/D0272RLLH45/p1686052869429119)
https://github.com/WasmEdge/WasmEdge/pull/2541. I have done most of the things. To avoid double work, please continue your work on this PR.
2. migrate the book content to this new repo since the 0.12.0 release, which needs to create a new PR on WasmEdge/doc
3. How to deal with the links to old books? The links have been everywhere. How to make sure the links still work and can direct users to the right content.

**Comment by alabulei1** [comment]
@juntao Do you have other ideas?

**Comment by alabulei1** [comment]
@adithyaakrishna  Please also take a look. This is part of GSoD.

**Comment by juntao** [comment]
Yes. I think we should not delete any page from the old book. Instead, we should change the pages to say:

This doc has moved to here.

We should do this for every single page in the old book as we build out the new book.

**Comment by adithyaakrishna** [comment]
Can we add like a admonition kinda thing? Similar to what we have in docusaurus? 

For example, a caution note?

<img width="686" alt="Screenshot 2023-06-07 at 11 33 29 AM" src="https://github.com/WasmEdge/docs/assets/23498248/00fade1a-41e1-44c2-a391-f2e7b7e151aa">

**Comment by alabulei1** [comment]
@adithyaakrishna according to the above comments. I think the first priority is to delete everything from MDBOOK because we must have one single source of truth. You can get started with my PR [#WasmEdge2541](https://github.com/WasmEdge/WasmEdge/pull/2541). Can you estimate when you can make the PR ready to merge?

For the content doesn't be migrated, please open a PR on WasmEdge/docs repo. Thanks.

**Comment by adithyaakrishna** [comment]
@juntao @alabulei1 Makes sense, I will proceed with the above PR. @alabulei1 I will clone that branch and checkout as a separate branch, then we can see how to proceed with other changes. To handle links to previous docs, we can set up redirection in MDBOOKS which can redirect us to the new docs

**Comment by JYC0413** [comment]
@flows_summarize
